# Generated by Django 4.0.3 on 2022-03-25 20:58

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="default.png", upload_to="profile_pics"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(editable=False, populate_from="user"),
                ),
                ("bio", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=255)),
                (
                    "personality_type",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "stay_go_type",
                    models.CharField(
                        choices=[
                            ("PI", "Prefer to Stay In"),
                            ("PO", "Prefer to Go Out"),
                        ],
                        max_length=50,
                    ),
                ),
                ("movie_choices", models.CharField(max_length=50)),
                (
                    "music_choices",
                    models.CharField(
                        choices=[
                            ("RO", "Rock"),
                            ("PO", "Pop"),
                            ("HIHO", "Hiphop"),
                            ("RP", "Rap"),
                            ("CL", "Classical"),
                            ("IN", "Indian"),
                            ("NI", "Not interested in Music"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "food_choices",
                    models.CharField(
                        choices=[
                            ("CA", "Caribbean"),
                            ("MX", "Mexican"),
                            ("MED", "Mediterranean"),
                            ("KO", "Korean"),
                            ("VT", "Vietnamese"),
                            ("IN", "Indian"),
                            ("CH", "Chinese"),
                            ("FN", "French"),
                            ("IT", "Italian"),
                            ("TH", "Thai"),
                            ("LB", "Lebanese"),
                            ("AM", "American"),
                            ("NI", "Not interested in Cooking/Cuisines"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "travel_choices",
                    models.CharField(
                        choices=[
                            ("MO", "Mountains"),
                            ("BE", "Beaches"),
                            ("DE", "Desserts"),
                            ("IP", "Ice Places"),
                            ("CT", "City"),
                            ("VI", "Village"),
                            ("NI", "Not interested in Traveling"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "art_choices",
                    models.CharField(
                        choices=[
                            ("DR", "Drawing"),
                            ("SK", "Sketching"),
                            ("PA", "Painting"),
                            ("PM", "Printmaking"),
                            ("JM", "Jewelery Making"),
                            ("PH", "Photography"),
                            ("SL", "Sculpture"),
                            ("CA", "Calligraphy"),
                            ("NI", "Not interested in Art"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "dance_choices",
                    models.CharField(
                        choices=[
                            ("HH", "HipHop"),
                            ("CP", "Contemporary"),
                            ("JZ", "Jazz"),
                            ("BL", "Ballet"),
                            ("BA", "Ballroom"),
                            ("TD", "Tap Dance"),
                            ("ID", "Irish Dance"),
                            ("BO", "Bollywood"),
                            ("SW", "Swing"),
                            ("NI", "Not interested in Dance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sports_choices",
                    models.CharField(
                        choices=[
                            ("FB", "Football"),
                            ("BK", "Basketball"),
                            ("CR", "Cricket"),
                            ("HC", "Hockey"),
                            ("BB", "Baseball"),
                            ("SB", "Softball"),
                            ("GM", "Gymnastics"),
                            ("SB", "Skateboard"),
                            ("RW", "Rowing"),
                            ("RB", "Rugby"),
                            ("LC", "Lacrosse"),
                            ("SW", "Swimming"),
                            ("SC", "Soccer"),
                            ("RU", "Running"),
                            ("VB", "Volleyball"),
                            ("SB", "Snowboarding"),
                            ("SK", "Skiing"),
                            ("MA", "Martial arts"),
                            ("GO", "Golf"),
                            ("BC", "Bicycling"),
                            ("NI", "Not interested in Sports"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "pet_choices",
                    models.CharField(
                        choices=[
                            ("DG", "Dogs"),
                            ("CT", "Cats"),
                            ("BI", "Birds"),
                            ("FI", "Fish"),
                            ("HR", "Horses"),
                            ("RT", "Reptiles"),
                            ("NI", "Not interested in Pets"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "nyc_choices",
                    models.CharField(
                        choices=[
                            ("MU", "Visiting Museum"),
                            ("CN", "Concerts"),
                            ("BA", "Bars"),
                            ("PK", "Park"),
                            ("CL", "Club"),
                            ("TH", "Theater"),
                            ("SW", "Street walk"),
                            ("NI", "Not interested in Exploring NYC"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
