# Generated by Django 4.0.2 on 2022-03-30 19:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="personality_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("VeryEX", "Very Extroverted"),
                    ("SomewhatEX", "Somewhat Extroverted"),
                    ("Neutral", "Neutral"),
                    ("SomewhatIN", "Somewhat Introverted"),
                    ("VeryIN", "Very Introverted"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
