# Generated by Django 4.0.2 on 2022-04-14 17:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='movie_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Movie_AC', 'Action'), ('Movie_CO', 'Comedy'), ('Movie_DR', 'Drama'), ('Movie_FN', 'Fantasy'), ('Movie_HR', 'Horror'), ('Movie_MY', 'Mystery'), ('Movie_RO', 'Romance'), ('Movie_TH', 'Thriller'), ('Movie_NI', 'Not interested in Movies')], max_length=100, null=True),
        ),
    ]
