# Generated by Django 4.0.3 on 2022-04-17 17:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='dance_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Dance_HH', 'Hip Hop'), ('Dance_CP', 'Contemporary'), ('Dance_JZ', 'Jazz'), ('Dance_BL', 'Ballet'), ('Dance_BA', 'Ballroom'), ('Dance_TD', 'Tap Dance'), ('Dance_ID', 'Irish Dance'), ('Dance_BO', 'Bollywood'), ('Dance_SW', 'Swing'), ('Dance_NI', 'Not interested in Dance')], max_length=89, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='music_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Music_RO', 'Rock'), ('MUSIC_PO', 'Pop'), ('MUSIC_HIHO', 'Hip hop'), ('MUSIC_RP', 'Rap'), ('MUSIC_CL', 'Classical'), ('MUSIC_IN', 'Indian'), ('MUSIC_NI', 'Not interested in Music')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='travel_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Travel_MO', 'Mountains'), ('Travel_BE', 'Beaches'), ('Travel_DE', 'Deserts'), ('Travel_IP', 'Ice Places'), ('Travel_CT', 'City'), ('Travel_VI', 'Village'), ('Travel_NI', 'Not interested in Traveling')], max_length=69, null=True),
        ),
    ]
