# Generated by Django 4.0.2 on 2022-04-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='declined_users',
        ),
        migrations.AddField(
            model_name='profile',
            name='seen_users',
            field=models.ManyToManyField(blank=True, related_name='seen_list', to='users.Profile'),
        ),
    ]
