# Generated by Django 4.0.2 on 2022-04-14 00:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="sports_choices",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Sports_FB", "Football"),
                    ("Sports_BK", "Basketball"),
                    ("Sports_CR", "Cricket"),
                    ("Sports_HC", "Hockey"),
                    ("Sports_BB", "Baseball"),
                    ("Sports_SFB", "Softball"),
                    ("Sports_GM", "Gymnastics"),
                    ("Sports_SKB", "Skateboard"),
                    ("Sports_RW", "Rowing"),
                    ("Sports_RB", "Rugby"),
                    ("Sports_LC", "Lacrosse"),
                    ("Sports_SW", "Swimming"),
                    ("Sports_SC", "Soccer"),
                    ("Sports_RU", "Running"),
                    ("Sports_VB", "Volleyball"),
                    ("Sports_SWB", "Snowboarding"),
                    ("Sports_SK", "Skiing"),
                    ("Sports_MA", "Martial arts"),
                    ("Sports_GO", "Golf"),
                    ("Sports_BC", "Bicycling"),
                    ("Sports_NI", "Not interested in Sports"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friend_list", to="users.Profile"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="seen_users",
            field=models.ManyToManyField(
                blank=True, related_name="seen_list", to="users.Profile"
            ),
        ),
    ]
