# Generated by Django 4.0.2 on 2022-03-26 22:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_preference_personality_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="movie_choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), size=None
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="personality_type",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                max_length=50,
            ),
        ),
    ]
