# Generated by Django 4.0.4 on 2022-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='blocked_list', to='users.profile'),
        ),
    ]
