# Generated by Django 4.0.2 on 2022-03-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_preference_bio_alter_preference_art_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='movie_choices',
            field=models.CharField(max_length=50),
        ),
    ]
