# Generated by Django 4.0.3 on 2022-05-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blockers",
            field=models.ManyToManyField(
                blank=True, related_name="blockers_list", to="users.profile"
            ),
        ),
    ]
