# Generated by Django 4.0.2 on 2022-03-26 22:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_preference_movie_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="movie_choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), size=None
            ),
        ),
    ]
