# Generated by Django 4.0.2 on 2022-03-26 22:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_preference_movie_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="movie_choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("AC", "Action"),
                        ("CO", "Comedy"),
                        ("DR", "Drama"),
                        ("FN", "Fantasy"),
                        ("HR", "Horror"),
                        ("MY", "Mystery"),
                        ("RO", "Romance"),
                        ("TH", "Thriller"),
                        ("NI", "Not interested in Movies"),
                    ],
                    max_length=50,
                ),
                size=None,
            ),
        ),
    ]
