# Generated by Django 4.0.2 on 2022-03-26 22:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_preference_art_choices_alter_preference_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="art_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DR", "Drawing"),
                    ("SK", "Sketching"),
                    ("PA", "Painting"),
                    ("PM", "Printmaking"),
                    ("JM", "Jewelery Making"),
                    ("PH", "Photography"),
                    ("SL", "Sculpture"),
                    ("CA", "Calligraphy"),
                    ("NI", "Not interested in Art"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="dance_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HH", "HipHop"),
                    ("CP", "Contemporary"),
                    ("JZ", "Jazz"),
                    ("BL", "Ballet"),
                    ("BA", "Ballroom"),
                    ("TD", "Tap Dance"),
                    ("ID", "Irish Dance"),
                    ("BO", "Bollywood"),
                    ("SW", "Swing"),
                    ("NI", "Not interested in Dance"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="food_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CA", "Caribbean"),
                    ("MX", "Mexican"),
                    ("MED", "Mediterranean"),
                    ("KO", "Korean"),
                    ("VT", "Vietnamese"),
                    ("IN", "Indian"),
                    ("CH", "Chinese"),
                    ("FN", "French"),
                    ("IT", "Italian"),
                    ("TH", "Thai"),
                    ("LB", "Lebanese"),
                    ("AM", "American"),
                    ("NI", "Not interested in Cooking/Cuisines"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="movie_choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("AC", "Action"),
                        ("CO", "Comedy"),
                        ("DR", "Drama"),
                        ("FN", "Fantasy"),
                        ("HR", "Horror"),
                        ("MY", "Mystery"),
                        ("RO", "Romance"),
                        ("TH", "Thriller"),
                        ("NI", "Not interested in Movies"),
                    ],
                    max_length=50,
                    null=True,
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="music_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RO", "Rock"),
                    ("PO", "Pop"),
                    ("HIHO", "Hiphop"),
                    ("RP", "Rap"),
                    ("CL", "Classical"),
                    ("IN", "Indian"),
                    ("NI", "Not interested in Music"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="nyc_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MU", "Visiting Museum"),
                    ("CN", "Concerts"),
                    ("BA", "Bars"),
                    ("PK", "Park"),
                    ("CL", "Club"),
                    ("TH", "Theater"),
                    ("SW", "Street walk"),
                    ("NI", "Not interested in Exploring NYC"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="personality_type",
            field=models.CharField(
                blank=True,
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="pet_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DG", "Dogs"),
                    ("CT", "Cats"),
                    ("BI", "Birds"),
                    ("FI", "Fish"),
                    ("HR", "Horses"),
                    ("RT", "Reptiles"),
                    ("NI", "Not interested in Pets"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="sports_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FB", "Football"),
                    ("BK", "Basketball"),
                    ("CR", "Cricket"),
                    ("HC", "Hockey"),
                    ("BB", "Baseball"),
                    ("SB", "Softball"),
                    ("GM", "Gymnastics"),
                    ("SB", "Skateboard"),
                    ("RW", "Rowing"),
                    ("RB", "Rugby"),
                    ("LC", "Lacrosse"),
                    ("SW", "Swimming"),
                    ("SC", "Soccer"),
                    ("RU", "Running"),
                    ("VB", "Volleyball"),
                    ("SB", "Snowboarding"),
                    ("SK", "Skiing"),
                    ("MA", "Martial arts"),
                    ("GO", "Golf"),
                    ("BC", "Bicycling"),
                    ("NI", "Not interested in Sports"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="stay_go_type",
            field=models.CharField(
                blank=True,
                choices=[("PI", "Prefer to Stay In"), ("PO", "Prefer to Go Out")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="travel_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MO", "Mountains"),
                    ("BE", "Beaches"),
                    ("DE", "Desserts"),
                    ("IP", "Ice Places"),
                    ("CT", "City"),
                    ("VI", "Village"),
                    ("NI", "Not interested in Traveling"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
