# Generated by Django 4.0.4 on 2022-05-05 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0007_report_reason_report_reported_report_reporter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reported",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reporter_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
