# Generated by Django 4.0.4 on 2022-05-06 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_report_reported_alter_report_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklisted', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
