# Generated by Django 4.0.2 on 2022-03-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_preference_art_choices_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preference",
            name="art_choices",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="dance_choices",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="food_choices",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="music_choices",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="nyc_choices",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="pet_choices",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="sports_choices",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="travel_choices",
        ),
    ]
