# Generated by Django 4.0.3 on 2022-03-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_preference_art_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='bio',
        ),
    ]
