# Generated by Django 4.0.3 on 2022-05-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_profile_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pronouns",
            field=models.CharField(
                blank=True,
                choices=[
                    ("She/her/hers", "She/her/hers"),
                    ("He/him/his", "He/him/his"),
                    ("They/them/theirs", "They/them/theirs"),
                    ("Prefer not to specify", "Prefer not to specify"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="school",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Arts and Science", "Arts and Science"),
                    ("College of Dentistry", "College of Dentistry"),
                    (
                        "Courant Institute of Mathematical Sciences",
                        "Courant Institute of Mathematical Sciences",
                    ),
                    (
                        "Gallatin School of Individualized Study",
                        "Gallatin School of Individualized Study",
                    ),
                    ("Grossman School of Medicine", "Grossman School of Medicine"),
                    (
                        "Long Island School of Medicine",
                        "Long Island School of Medicine",
                    ),
                    ("Institute of Fine Arts", "Institute of Fine Arts"),
                    (
                        "Institute for the Study of Ancient World",
                        "Institute for the Study of Ancient World",
                    ),
                    ("Meyers College of Nursing", "Meyers College of Nursing"),
                    ("School of Law", "School of Law"),
                    (
                        "School of Global Public Health",
                        "School of Global Public Health",
                    ),
                    ("NYU Abu Dhabi", "NYU Abu Dhabi"),
                    ("NYU Shanghai", "NYU Shanghai"),
                    (
                        "School of Professional Studies",
                        "School of Professional Studies",
                    ),
                    ("Silver School of Social Work", "Silver School of Social Work"),
                    (
                        "Steinhardt School of Culture, Education, and Human Development",
                        "Steinhardt School of Culture, Education, and Human Development",
                    ),
                    ("Stern School of Business", "Stern School of Business"),
                    ("Tandon School of Engineering", "Tandon School of Engineering"),
                    ("Tisch School of the Arts", "Tisch School of the Arts"),
                    (
                        "Wagner Graduate School of Public Service",
                        "Wagner Graduate School of Public Service",
                    ),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Freshman", "Freshman"),
                    ("Sophomore", "Sophomore"),
                    ("Junior", "Junior"),
                    ("Senior", "Senior"),
                    ("Graduate Student", "Graduate Student"),
                    ("PhD Student", "PhD Student"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
