# Generated by Django 4.0.3 on 2022-05-10 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_friendrequest_from_user_and_more"),
        ("users", "0013_alter_profile_pronouns_alter_profile_school_and_more"),
    ]

    operations = []
