language: python

python:
  - "3.9"

env:
  - DJANGO=4.2.0

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database nyunite_test;' -U postgres

script:
  - black . --check
  - flake8 --count
  - coverage run manage.py test

after_success:
  - coveralls