MOVIES_CHOICES = [
    ("Movie_AC", "Action"),
    ("Movie_CO", "Comedy"),
    ("Movie_DR", "Drama"),
    ("Movie_FN", "Fantasy"),
    ("Movie_HR", "Horror"),
    ("Movie_MY", "Mystery"),
    ("Movie_RO", "Romance"),
    ("Movie_TH", "Thriller"),
    ("Movie_NI", "Not interested in Movies"),
]
MUSIC_CHOICES = [
    ("Music_RO", "Rock"),
    ("MUSIC_PO", "Pop"),
    ("MUSIC_HIHO", "Hip hop"),
    ("MUSIC_RP", "Rap"),
    ("MUSIC_CL", "Classical"),
    ("MUSIC_IN", "Indian"),
    ("MUSIC_NI", "Not interested in Music"),
]
COOKEAT_CHOICES = [
    ("Cookeat_CA", "Caribbean"),
    ("Cookeat_MX", "Mexican"),
    ("Cookeat_MED", "Mediterranean"),
    ("Cookeat_KO", "Korean"),
    ("Cookeat_VT", "Vietnamese"),
    ("Cookeat_IN", "Indian"),
    ("Cookeat_CH", "Chinese"),
    ("Cookeat_FN", "French"),
    ("Cookeat_IT", "Italian"),
    ("Cookeat_TH", "Thai"),
    ("Cookeat_LB", "Lebanese"),
    ("Cookeat_AM", "American"),
    ("Cookeat_NI", "Not interested in Cooking/Cuisines"),
]
TRAVEL_CHOICES = [
    ("Travel_NP", "National Park"),
    ("Travel_BE", "Beach"),
    ("Travel_DE", "Desert"),
    ("Travel_CT", "City"),
    ("Travel_IS", "Island"),
    ("Travel_NI", "Not interested in Traveling"),
]
ART_CHOICES = [
    ("Art_DR", "Drawing"),
    ("Art_SK", "Sketching"),
    ("Art_PA", "Painting"),
    ("Art_PM", "Printmaking"),
    ("Art_JM", "Jewelery Making"),
    ("Art_PH", "Photography"),
    ("Art_SL", "Sculpture"),
    ("Art_CA", "Calligraphy"),
    ("Art_NI", "Not interested in Art"),
]
DANCE_CHOICES = [
    ("Dance_HH", "Hip Hop"),
    ("Dance_CP", "Contemporary"),
    ("Dance_JZ", "Jazz"),
    ("Dance_BL", "Ballet"),
    ("Dance_BA", "Ballroom"),
    ("Dance_TD", "Tap Dance"),
    ("Dance_ID", "Irish Dance"),
    ("Dance_BO", "Bollywood"),
    ("Dance_SW", "Swing"),
    ("Dance_NI", "Not interested in Dance"),
]
SPORTS_CHOICES = [
    ("Sports_FB", "Football"),
    ("Sports_BK", "Basketball"),
    ("Sports_CR", "Cricket"),
    ("Sports_HC", "Hockey"),
    ("Sports_BB", "Baseball"),
    ("Sports_SFB", "Softball"),
    ("Sports_GM", "Gymnastics"),
    ("Sports_SKB", "Skateboard"),
    ("Sports_RW", "Rowing"),
    ("Sports_RB", "Rugby"),
    ("Sports_LC", "Lacrosse"),
    ("Sports_SW", "Swimming"),
    ("Sports_SC", "Soccer"),
    ("Sports_RU", "Running"),
    ("Sports_VB", "Volleyball"),
    ("Sports_SWB", "Snowboarding"),
    ("Sports_SK", "Skiing"),
    ("Sports_MA", "Martial arts"),
    ("Sports_GO", "Golf"),
    ("Sports_BC", "Bicycling"),
    ("Sports_NI", "Not interested in Sports"),
]
PET_CHOICES = [
    ("Pet_DG", "Dogs"),
    ("Pet_CT", "Cats"),
    ("Pet_BI", "Birds"),
    ("Pet_FI", "Fish"),
    ("Pet_HR", "Horses"),
    ("Pet_RT", "Reptiles"),
    ("Pet_NI", "Not interested in Pets"),
]
PERSONALITY_CHOICES = [
    ("Personality_VeryEX", "Very Extroverted"),
    ("Personality_SomewhatEX", "Somewhat Extroverted"),
    ("Personality_Neutral", "Neutral"),
    ("Personality_SomewhatIN", "Somewhat Introverted"),
    ("Personality_VeryIN", "Very Introverted"),
]
STAY_GO_CHOICES = [
    ("Staygo_PI", "Prefer to Stay In"),
    ("Staygo_PO", "Prefer to Go Out"),
]
NYC_CHOICES = [
    ("Nyc_MU", "Visiting Museum"),
    ("Nyc_CN", "Concerts"),
    ("Nyc_BA", "Bars"),
    ("Nyc_PK", "Park"),
    ("Nyc_CL", "Club"),
    ("Nyc_TH", "Theater"),
    ("Nyc_SW", "Street walk"),
    ("Nyc_NI", "Not interested in Exploring NYC"),
]
interests_choices = {
    "Movie_AC": "Action",
    "Movie_CO": "Comedy",
    "Movie_DR": "Drama",
    "Movie_FN": "Fantasy",
    "Movie_HR": "Horror",
    "Movie_MY": "Mystery",
    "Movie_RO": "Romance",
    "Movie_TH": "Thriller",
    "Movie_NI": "Not interested in Movies",
    "Music_RO": "Rock",
    "MUSIC_PO": "Pop",
    "MUSIC_HIHO": "Hip hop",
    "MUSIC_RP": "Rap",
    "MUSIC_CL": "Classical",
    "MUSIC_IN": "Indian",
    "MUSIC_NI": "Not interested in Music",
    "Cookeat_CA": "Caribbean",
    "Cookeat_MX": "Mexican",
    "Cookeat_MED": "Mediterranean",
    "Cookeat_KO": "Korean",
    "Cookeat_VT": "Vietnamese",
    "Cookeat_IN": "Indian",
    "Cookeat_CH": "Chinese",
    "Cookeat_FN": "French",
    "Cookeat_IT": "Italian",
    "Cookeat_TH": "Thai",
    "Cookeat_LB": "Lebanese",
    "Cookeat_AM": "American",
    "Cookeat_NI": "Not interested in Cooking/Cuisines",
    "Travel_NP": "National Park",
    "Travel_BE": "Beach",
    "Travel_DE": "Desert",
    "Travel_CT": "City",
    "Travel_IS": "Island",
    "Travel_NI": "Not interested in Traveling",
    "Art_DR": "Drawing",
    "Art_SK": "Sketching",
    "Art_PA": "Painting",
    "Art_PM": "Printmaking",
    "Art_JM": "Jewelery Making",
    "Art_PH": "Photography",
    "Art_SL": "Sculpture",
    "Art_CA": "Calligraphy",
    "Art_NI": "Not interested in Art",
    "Dance_HH": "Hip Hop",
    "Dance_CP": "Contemporary",
    "Dance_JZ": "Jazz",
    "Dance_BL": "Ballet",
    "Dance_BA": "Ballroom",
    "Dance_TD": "Tap Dance",
    "Dance_ID": "Irish Dance",
    "Dance_BO": "Bollywood",
    "Dance_SW": "Swing",
    "Dance_NI": "Not interested in Dance",
    "Sports_FB": "Football",
    "Sports_BK": "Basketball",
    "Sports_CR": "Cricket",
    "Sports_HC": "Hockey",
    "Sports_BB": "Baseball",
    "Sports_SFB": "Softball",
    "Sports_GM": "Gymnastics",
    "Sports_SKB": "Skateboard",
    "Sports_RW": "Rowing",
    "Sports_RB": "Rugby",
    "Sports_LC": "Lacrosse",
    "Sports_SW": "Swimming",
    "Sports_SC": "Soccer",
    "Sports_RU": "Running",
    "Sports_VB": "Volleyball",
    "Sports_SWB": "Snowboarding",
    "Sports_SK": "Skiing",
    "Sports_MA": "Martial arts",
    "Sports_GO": "Golf",
    "Sports_BC": "Bicycling",
    "Sports_NI": "Not interested in Sports",
    "Pet_DG": "Dogs",
    "Pet_CT": "Cats",
    "Pet_BI": "Birds",
    "Pet_FI": "Fish",
    "Pet_HR": "Horses",
    "Pet_RT": "Reptiles",
    "Pet_NI": "Not interested in Pets",
    "Personality_VeryEX": "Very Extroverted",
    "Personality_SomewhatEX": "Somewhat Extroverted",
    "Personality_Neutral": "Neutral",
    "Personality_SomewhatIN": "Somewhat Introverted",
    "Personality_VeryIN": "Very Introverted",
    "Staygo_PI": "Prefer to Stay In",
    "Staygo_PO": "Prefer to Go Out",
    "Nyc_MU": "Visiting Museum",
    "Nyc_CN": "Concerts",
    "Nyc_BA": "Bars",
    "Nyc_PK": "Park",
    "Nyc_CL": "Club",
    "Nyc_TH": "Theater",
    "Nyc_SW": "Street walk",
    "Nyc_NI": "Not interested in Exploring NYC",
}
