MOVIES_CHOICES = [
    ("AC", "Action"),
    ("CO", "Comedy"),
    ("DR", "Drama"),
    ("FN", "Fantasy"),
    ("HR", "Horror"),
    ("MY", "Mystery"),
    ("RO", "Romance"),
    ("TH", "Thriller"),
    ("NI", "Not interested in Movies"),
]
MUSIC_CHOICES = [
    ("RO", "Rock"),
    ("PO", "Pop"),
    ("HIHO", "Hiphop"),
    ("RP", "Rap"),
    ("CL", "Classical"),
    ("IN", "Indian"),
    ("NI", "Not interested in Music"),
]
COOKEAT_CHOICES = [
    ("CA", "Caribbean"),
    ("MX", "Mexican"),
    ("MED", "Mediterranean"),
    ("KO", "Korean"),
    ("VT", "Vietnamese"),
    ("IN", "Indian"),
    ("CH", "Chinese"),
    ("FN", "French"),
    ("IT", "Italian"),
    ("TH", "Thai"),
    ("LB", "Lebanese"),
    ("AM", "American"),
    ("NI", "Not interested in Cooking/Cuisines"),
]
TRAVEL_CHOICES = [
    ("MO", "Mountains"),
    ("BE", "Beaches"),
    ("DE", "Desserts"),
    ("IP", "Ice Places"),
    ("CT", "City"),
    ("VI", "Village"),
    ("NI", "Not interested in Traveling"),
]
ART_CHOICES = [
    ("DR", "Drawing"),
    ("SK", "Sketching"),
    ("PA", "Painting"),
    ("PM", "Printmaking"),
    ("JM", "Jewelery Making"),
    ("PH", "Photography"),
    ("SL", "Sculpture"),
    ("CA", "Calligraphy"),
    ("NI", "Not interested in Art"),
]
DANCE_CHOICES = [
    ("HH", "HipHop"),
    ("CP", "Contemporary"),
    ("JZ", "Jazz"),
    ("BL", "Ballet"),
    ("BA", "Ballroom"),
    ("TD", "Tap Dance"),
    ("ID", "Irish Dance"),
    ("BO", "Bollywood"),
    ("SW", "Swing"),
    ("NI", "Not interested in Dance"),
]
SPORTS_CHOICES = [
    ("FB", "Football"),
    ("BK", "Basketball"),
    ("CR", "Cricket"),
    ("HC", "Hockey"),
    ("BB", "Baseball"),
    ("SB", "Softball"),
    ("GM", "Gymnastics"),
    ("SB", "Skateboard"),
    ("RW", "Rowing"),
    ("RB", "Rugby"),
    ("LC", "Lacrosse"),
    ("SW", "Swimming"),
    ("SC", "Soccer"),
    ("RU", "Running"),
    ("VB", "Volleyball"),
    ("SB", "Snowboarding"),
    ("SK", "Skiing"),
    ("MA", "Martial arts"),
    ("GO", "Golf"),
    ("BC", "Bicycling"),
    ("NI", "Not interested in Sports"),
]
PET_CHOICES = [
    ("DG", "Dogs"),
    ("CT", "Cats"),
    ("BI", "Birds"),
    ("FI", "Fish"),
    ("HR", "Horses"),
    ("RT", "Reptiles"),
    ("NI", "Not interested in Pets"),
]
PERSONALITY_CHOICES = [
    ("VeryEX", "Very Extroverted"),
    ("SomewhatEX", "Somewhat Extroverted"),
    ("Neutral", "Neutral"),
    ("SomewhatIN", "Somewhat Introverted"),
    ("VeryIN", "Very Introverted"),
]
STAY_GO_CHOICES = [
    ("PI", "Prefer to Stay In"),
    ("PO", "Prefer to Go Out"),
]
NYC_CHOICES = [
    ("MU", "Visiting Museum"),
    ("CN", "Concerts"),
    ("BA", "Bars"),
    ("PK", "Park"),
    ("CL", "Club"),
    ("TH", "Theater"),
    ("SW", "Street walk"),
    ("NI", "Not interested in Exploring NYC"),
]
