# Generated by Django 4.0.2 on 2022-02-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uniqueID', models.BigAutoField(primary_key=True, serialize=False)),
                ('netID', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=1, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('password1', models.CharField(max_length=32)),
                ('password2', models.CharField(max_length=32)),
            ],
        ),
    ]
