# Generated by Django 4.0.2 on 2022-02-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
        migrations.AddField(
            model_name='user',
            name='email_bak',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
