# Generated by Django 4.0.2 on 2022-03-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_password2_user_email_bak'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetails',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='password1',
            new_name='password',
        ),
    ]
